name       : koji
version    : 1.16.1
release    : 5
source     :
    - https://releases.pagure.org/koji/koji-1.16.1.tar.bz2 : e51c834f0d7e83a0e07561225402c3249f6bc5ee447d3a8d601074e52e240806
license    : GPL-2.0-or-later
component  : programming.tools
summary    : RPM Build System
description: |
    RPM Build System
rundeps    :
    - mock
    - rpm
    - python-krbv
build      : |
    %make
install    : |
    %make_install
